### ISSUE TITLE
How do I install python package into the interpreter that ops uses?

### ISSUE THREAD

**Issue by geekjr** [nanovms/ops-documentation#113]
How do I install python package into the interpreter that ops uses?

**Comment by eyberg** [comment]
this is one way ->

essentially you do a user install && then map your local directory over ->

https://github.com/nanovms/ops-examples/tree/master/python2.7/03-flask-hello-world

https://github.com/nanovms/ops-examples/blob/master/python2.7/03-flask-hello-world/config.json#L3

we could definitely use more docs on this

https://github.com/nanovms/ops-examples/issues/38
