### ISSUE TITLE
Ops instance create failed in azure

### ISSUE THREAD

**Issue by rajagopalanrg** [nanovms/ops-documentation#151]
when trying to create instance in azure with Ops, it fails with creating virtual networks

**Comment by fabioDMFerreira** [comment]
@rajagopalanrg thanks for your report. Could you run the command with the flag `--show-debug` and let me know which is the output?

**Comment by rajagopalanrg** [comment]
Hi @fabioDMFerreira , I was able to create a VM in azure but it takes a little longer compared to AWS. I noticed that it creates a virtual network, subnet and nsg every time I create an instance. Is there any way to optimize it?

**Comment by fabioDMFerreira** [comment]
@rajagopalanrg sure, you can reuse the virtual network/subnet/nsg.

Add the next keys to your configuration file:
```
{
  "RunConfig": {
   	VPC: "virtual network",
	SecurityGroup:"nsg",
	Subnet :"subnet"
   }
 }
```

**Comment by rajagopalanrg** [comment]
@fabioDMFerreira  it works now!! thank you. Is there any detailed documentation on other configuration details for azure and was?

**Comment by fabioDMFerreira** [comment]
See below aws and azure documentation pages:
- https://nanovms.gitbook.io/ops/azure
- https://nanovms.gitbook.io/ops/aws

Ops documentation must be updated with notes about reusing virtual network/subnet/security group. Created the ticket https://github.com/nanovms/ops-documentation/issues/152.

**Comment by fabioDMFerreira** [comment]
I'm considering this issue as closed since you are now able to create instances in azure.

**Comment by rajagopalanrg** [comment]
yes, this can be closed.
