### ISSUE TITLE
How to get metrics of instances created in cloud

### ISSUE THREAD

**Issue by rajagopalanrg** [nanovms/ops-documentation#155]
Hi, I tried creating instances in aws and azure but is there a way to get metrics(cpu and memory usage) of those?

**Comment by eyberg** [comment]
@rajagopalanrg - most clouds will show you cpu utilization (and is accessible through their respective apis) - we are looking at rolling that into ops as well -> https://github.com/nanovms/ops/issues/832

for memory - that is something that nanos has to export itself, you can use existing in-app agents for that (prometheus, etc.) but we are also working on a way of exporting that in a different/easier manner as well - so stay tuned for that
