### ISSUE TITLE
need differentiation on nightly flag versus force download

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-documentation#23]
the behavior for this changed recently

it used to be that '-f' would download whatever was in nightly

now '-f' just forces download whatever you are tracking && '-n' does nightly so it seems '-n' && '-f' together is the bleeding edge

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops-documentation/pull/26

**Comment by eyberg** [comment]
thanks
