### ISSUE TITLE
adding a comparison against other unikernels

### ISSUE THREAD

**Issue by iamshreeram** [nanovms/ops-documentation#268]
It would be good if we can add a documentation page that shows the comparison between other Library OS'es in the market. We can initially begin with the OS that are implemented on POSIX standards (Graphene, Rumprun, etc..). 

### Why is this needed?
It is easy for developers to get lost on large list of OS available in the market. The documentation can give a hint/should describe 
1. when should some one use nanovms instead of MirageOS, Rumprun, Graphene etc..
2. the void that nanovms fill in and the drawbacks that other OSes have

A simple table should suffice. Any thoughts?

**Comment by eyberg** [comment]
this exists on the nanos.org page -> https://nanos.org/faq

**Comment by iamshreeram** [comment]
Thanks! This table gives the perfect overview. 

1. Is there any reason for not having this doc in the nanosvms.com page? 
2. **Functions** of Nanos in the table is described as "Cloud & Edge". Should we add some more to it? For e.g., We are able to run microservices created in python via nanovms. We can add Microservices I believe. 
3. Also, Can we add a column that describes when a user must choose Nanovms when compared against all other unikernels? (Some core reason where Nanovm stand out of other unikernels or why Nanovm was created)

**Comment by eyberg** [comment]
well nanovms.com is the company page and we are intentionally keeping the community projects separate on their own websites, as for why not on the ops.city page - this is nanos specific information and probably belongs on the nanos website

I think after some cleanup we can probably look at opening the nanos.org website to community edits, i can't think of any reason why it should stay private

**Comment by iamshreeram** [comment]
Sounds good.
