### ISSUE TITLE
Error on bhyve

### ISSUE THREAD

**Issue by blastrider** [nanovms/ops-documentation#288]
Hi, i just discovered your technology and i'm interested in using it in a production environment within HardenedBSD.

I make tests on FreeBSD to see how it works but, following the procedure you put there : https://docs.ops.city/ops/bhyve

i didn't succeded to run the kernel. I have the following error inside Bhyve : `couldn't find program interpreter /libexec/ld-elf.so.1`

Everything went great before, but this point locks. And i can run other VMs...

The other point is that i'm still lokking for FreeBSD 13.6.0 :)

Well if you can answer.

Thanks !

**Comment by eyberg** [comment]
hi @blastrider the bsd support is fairly limited right now - did you build a nanos image on linux first and tried to run it on hardened/fbsd? how were you building the image? do you an example to look at?

**Comment by eyberg** [comment]
as for 13.6.0 - that's definitely a typo - it should be 13.0

**Comment by blastrider** [comment]
In fact I built the image on freebsd 13.
I followed the way you shown on your site, here : https://nanovms.com/dev/tutorials/running-unikernels-on-bhyve-hypervisor-on-freebsd
I built ops from sources by cloning the git (freebsd isn't supported by the script 😭).
Il used truss to debug the build and to debug the bhyve command too. 
Everything works well freebsd side, and on hardened with and without security on, I have twice the same error.
Using qemu on freebsd by itself threw the same error.
But it really seems that libexec/ld-elf.so.1 is unreachable while booting the vm. 1 case on 2 my bhyve vm gets an ip from my local dhcp server.
And I didn't try a Linux build first then a bhyve run, I'll try maybe, but I really want to find a way to make the full architecture on hardened BSD.

**Comment by eyberg** [comment]
if you're using the go example in the article that should work but if you are trying a random fbsd binary there is no support in ops for building/running binaries on fbsd currently - that's prob what you are hitting?

**Comment by blastrider** [comment]
On freebsd 13 : 
I compiled ops from the git repo then I built it : 
make deps
make build
Then I copied the binary to /usr/local/bin/. 
ops version returned the good version. 
Then i made this procedure : 
https://nanovms.com/dev/tutorials/running-unikernels-on-bhyve-hypervisor-on-freebsd
But if the ops builder doesn't have to work on freebsd, it's my bad, I didn't understand 😔. 
Can I (not in the few day but one moment) contribute to make a bsd working ops builder? Or if it's not the way you want to go, can I fork it?

**Comment by eyberg** [comment]
right now ops can only run nanos images that are pre-built (eg: built on linux or mac) - it can't build them natively on fbsd currently unless that are fully statically linked, idk if there are nanos changes that need to occur but there is definitely some ops changes that would need to occur to resolve any dynamically linked libraries

**Comment by blastrider** [comment]
OK thank you for answering 😊.
Running hbsd as principal OS, il will probably try to run it natively. I understand that you prefer to pay attention to Linux and MacOS 😉.
Your project is really good and I will let you know if I succeed to run it on fbsd and hbsd natively 😉. 
Wish you the best and see you soon 👍
