### ISSUE TITLE
sinatra example

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-documentation#30]
taken from - https://github.com/nanovms/ops/issues/198 it'd be good to have a sinatra example

hello world is great - but a pre-baked framework that ppl actually use is better

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/issues/214

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-examples/tree/master/ruby/02-http-hello-world
