### ISSUE TITLE
add ltrace docs

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-documentation#349]
add notes on using ltrace https://github.com/nanovms/nanos/pull/1793

in particular I believe this only works if programs are compiled with -no-pie (which is not the default and implies no aslr)

**Comment by francescolavra** [comment]
Actually it works on both pie and no-pie programs, and also works with aslr.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-documentation/pull/350
