### ISSUE TITLE
clarify which clouds we have hot-plug support on volumes with

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-documentation#418]
pretty sure either aws &&|| gcp have it - probably no others

**Comment by francescolavra** [comment]
We have volume hotplug support on AWS (https://github.com/nanovms/nanos/pull/1573 && https://github.com/nanovms/nanos/pull/1631), GCP (https://github.com/nanovms/nanos/pull/1628), and Azure (https://github.com/nanovms/nanos/pull/1710)

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-documentation/pull/442
