### ISSUE TITLE
add docs for revised reboot_on_exit

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops-documentation#445]
https://github.com/nanovms/nanos/pull/1977

~~specifically need to mention that enabling 'reboot on any' (vs reboot on non-zero) can make poweroff/stop operations not operate as well they should (eg: take forever to shutdown, data corruption, etc.)~~

**Comment by francescolavra** [comment]
The changes we made in https://github.com/nanovms/nanos/pull/1975 make poweroff/stop operations work normally, regardless of the presence and value of the reboot_on_exit option, and regardless of the application exit code. Basically the kernel is now checking whether a kernel shutdown has been triggered by a poweroff/stop request, and if this is the case it does the shutdown ignoring the reboot_on_exit option

**Comment by eyberg** [comment]
excellent - that sounds way better
