### ISSUE TITLE
the secret of "The configuration file used by ops"

### ISSUE THREAD

**Issue by dimyme** [nanovms/ops-documentation#75]
at https://nanovms.gitbook.io/ops/configuration you seem to be talking about one ominous file with a secret filename and a secret path.

do you care to elucidate whereabouts in the dirtree that file (referred to in a conspicuous :ghost:  manner only as **"The configuration file used by ops "**) might be located under which name or is it safe to assume that both path and filename have the value **NUL** as you seem to imply?

**Comment by eyberg** [comment]
thanks for filing this issue - the file in question is whatever you pass in via the '-c' flag - it's not required but for any non-top application it'll prob. be used

for example in 'ops load' ->

```
➜  ~  ops load
Error: requires at least 1 arg(s), only received 0
Usage:
  ops load [packagename] [flags]

Flags:
  -x, --accel              use cpu virtualization extension
  -a, --args stringArray   command line arguments
  -b, --bridged            bridge networking
  -c, --config string      ops config file
....
```

by default in most of our examples you'll see it as 'config.json'

so for a python example if you look at this example -> https://github.com/nanovms/ops-examples/tree/master/python3.6/02-http-hello-world - you can pass it in as such https://github.com/nanovms/ops-examples/blob/master/python3.6/02-http-hello-world/config.json

does that make sense?

if so please feel free to open up a PR with any clarifying language

**Comment by dimyme** [comment]
yes this cogent answer ought to clarify about this enigmatic file.   At https://nanovms.gitbook.io/ops/configuration one might write thus sth. like:

**"The configuration file used by ops (such as one passed as parameter, e.g.  ops --config myconfig.json ... ) specifies various options and attributes of code execution, [...]"**
